# Generated by Django 4.0.2 on 2023-02-09 19:45

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(blank=True)),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_email', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=account.models.checkImage)),
                ('token', models.CharField(blank=True, max_length=300)),
                ('default_size', models.IntegerField(choices=[(102400, '100 MB'), (204800, '200 MB'), (409600, '400 MB'), (614400, '600 MB'), (819200, '800 MB'), (1048576, '1GB'), (2097152, '2GB'), (3145728, '3GB'), (4194304, '4GB'), (5242880, '5GB')], default=204800)),
                ('uploaded_size', models.IntegerField(blank=True, default=0)),
                ('active_email', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userfeedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles2',
            fields=[
                ('file', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('password', models.CharField(default='none', max_length=8)),
                ('file_name', models.CharField(max_length=255)),
                ('file_ext', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser')),
            ],
        ),
        migrations.CreateModel(
            name='ShareFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('reciver', models.CharField(blank=True, max_length=255)),
                ('file_id', models.FileField(blank=True, null=True, upload_to=account.models.share_func)),
                ('reciver_checked', models.BooleanField(default=False)),
                ('reciver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser')),
            ],
        ),
        migrations.CreateModel(
            name='ShareFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('reciver', models.CharField(blank=True, max_length=255)),
                ('file_id', models.FileField(blank=True, null=True, upload_to=account.models.share_func)),
                ('reciver_checked', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=300)),
                ('reciver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser')),
            ],
        ),
        migrations.CreateModel(
            name='NonRegisterFolderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(blank=True, max_length=255)),
                ('file', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('insert_time', models.DateTimeField(null=True)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('validity', models.CharField(blank=True, max_length=20)),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser')),
            ],
        ),
        migrations.CreateModel(
            name='FolderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(unique=True, upload_to='')),
                ('only_file_name', models.TextField(blank=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.folder')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser'),
        ),
        migrations.CreateModel(
            name='DeletedFileFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
                ('folder_name', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('shared', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser')),
            ],
        ),
    ]
