# Generated by Django 4.1.6 on 2023-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_folderfile_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderfile',
            name='file_name',
            field=models.FileField(max_length=200, unique=True, upload_to=''),
        ),
    ]
