# Generated by Django 4.1.6 on 2023-06-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_folderfile_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderfile',
            name='files',
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='folderfile',
            name='file_name',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
