# Generated by Django 4.1.6 on 2023-06-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_folderfile_files_folder_folder_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='folderfile',
            name='file_name',
            field=models.FileField(max_length=200, unique=True, upload_to=''),
        ),
    ]
