# Generated by Django 4.1.6 on 2023-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_folder_folder_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder_password',
        ),
        migrations.AddField(
            model_name='folderfile',
            name='files',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
