# Generated by Django 4.1.6 on 2023-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_folderfile_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderfile',
            name='file_name',
            field=models.FileField(max_length=255, unique=True, upload_to=''),
        ),
    ]
