# Generated by Django 4.1.6 on 2023-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_folderfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderfile',
            name='trash_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
