# Generated by Django 4.1.6 on 2023-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_deletedfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DeletedFolder',
        ),
    ]
