# Generated by Django 4.1.6 on 2023-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_folder_is_locked_delete_deletedfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_password',
            field=models.CharField(max_length=200),
        ),
    ]
