# Generated by Django 4.1.6 on 2023-06-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_folder_folder_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
