# Generated by Django 4.1.6 on 2023-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_folder_folder_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='pass_present',
            field=models.BooleanField(default=False),
        ),
    ]
