# Generated by Django 4.1.6 on 2023-08-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_folder_pass_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderfile',
            name='file_name',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
