# Generated by Django 4.1.6 on 2023-08-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_folderfile_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryDeletedFileFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(blank=True, max_length=255, upload_to='')),
                ('folder_name', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser')),
            ],
        ),
    ]
