# Generated by Django 4.1.6 on 2023-08-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_recoverydeletedfilefolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='folderfile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nonregisterfolderfile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sharefile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sharefolder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
