# Generated by Django 4.1.6 on 2023-08-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_folder_created_date_folderfile_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
