# Generated by Django 4.1.6 on 2023-08-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_folder_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderfile',
            name='file_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
